env:
  browser: true
extends:
  - 'plugin:react/recommended'
  - 'airbnb'
  - 'airbnb/hooks'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2019
  sourceType: module
plugins:
  - react
rules: { }
